version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::832585910212:user/aws-sam-cli-managed-dev-pipeline-resou-PipelineUser-8pGq1mlOCrbx"
permissions_provider = "AWS IAM"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::832585910212:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-Xvd0TkcaNzFN"
cloudformation_execution_role = "arn:aws:iam::832585910212:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-rXTsdzov6kZe"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-1w7qf3wnvv9mk"
image_repository = ""
region = "us-east-1"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::832585910212:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-sRXbqPlhAPn2"
cloudformation_execution_role = "arn:aws:iam::832585910212:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-CG8gA8C9J1ga"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-1hdtex7g4n3ce"
image_repository = ""
region = "us-east-1"
